### PR TITLE
Bump sdk

### PR DESCRIPTION
**Pull request by buvinghausen**

### CODE REVIEW

**Review by jnm2 — APPROVED** [review]

**Comment by buvinghausen** [comment]
@jnm2 it appears they pulled .net core 2.1 and 3.1 runtimes from the base image

2020-08-27T21:09:21.6676194Z The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
2020-08-27T21:09:22.7219602Z The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

**Comment by jnm2** [comment]
@buvinghausen Perhaps the installation step caused the SDK to stop finding the installed frameworks.

**Comment by jnm2** [comment]
The easiest thing might be to add two more installation steps for now. They would be runtime installations instead of SDK installations.

**Comment by buvinghausen** [comment]
@jnm2 yeah we only need the runtimes and not additional sdks.  Do you know if there is a runtime installing action available off hand?

**Comment by jnm2** [comment]
@buvinghausen It's usually a parameter of the same action.

**Comment by jnm2** [comment]
Hmm, doesn't look like this one supports that. Also: https://github.com/actions/setup-dotnet/issues/25

**Comment by jnm2** [comment]
Maybe we have to `https://dot.net/v1/dotnet-install.ps1` directly: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script. It has a `--runtime`/`-Runtime` switch that installs just the runtime instead of the whole SDK.

Here's a place where I did that:
https://github.com/nunit/nunit/blob/11ebd486b11e535c774f0de17910d6907a847724/appveyor.yml#L7-L9

**Comment by buvinghausen** [comment]
@jnm2 yeah you can see who the last commenter on setup-dotnet 25 is.... ha

I'll see if I have any luck with the install script because it definitely would be nice to be able to include the runtimes for testing and not have to wait on the official image to update or maintain.

**Comment by buvinghausen** [comment]
@jnm2 it feels dirty installing 3 SDKs when you need 1 SDK and 2 runtimes but I followed the SxS advice on setup-dotnet #25 and it works so for now I'm just going to leave it in and we can optimize later if the time ever comes.

**Pull request merged**
